# Generated by Django 5.1.6 on 2025-02-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('electronic', 'Electronic'), ('books', 'Books')], default='clothing', max_length=100),
        ),
    ]
