# Generated by Django 5.1.6 on 2025-02-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_inventory_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='null', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
